version: "3.9"

services:
  postgres1:
    image: postgres:16.2
    ports:
      - "5431:5432/tcp"
    environment:
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "user"
      POSTGRES_DB: "foqs"

  postgres2:
    image: postgres:16.2
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "user"
      POSTGRES_DB: "foqs"

  postgres3:
    image: postgres:16.2
    ports:
      - "5433:5432/tcp"
    environment:
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "user"
      POSTGRES_DB: "foqs"

  postgres4:
    image: postgres:16.2
    ports:
      - "5434:5432/tcp"
    environment:
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "user"
      POSTGRES_DB: "foqs"
